front/urls.py
from django.urls import path
from . import views

app_name="front"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login, name="login"),
    path("register", views.register, name="register"),
    path("add", views.add, name="add")
]

taski/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include("front.urls"))
]

front/models.py
from django.db import models

# Create your models here.

front/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms;

tasks=[]

class NewTaskForm(forms.Form):
    task= forms.CharField(label="Add Task")
    priority= forms.IntegerField(label="Pritority", min_value=1, max_value=10)

# Create your views here.
def index(request):
    return render(request, "front/index.html", {
        "tasks": tasks
    })
 
def login(request):
    return render(request, "front/login.html")

def register(request):
    return render(request, "front/register.html")

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            tasks.append(task)
        else:
            return render(request, "front/add.html", {
                "form": form
            })


    return render(request, "front/add.html", {
        "form": NewTaskForm()
    })

front/templates/front/add.html
{% extends 'front/base.html' %}


{% block body %}
    <h1>Add a Task.</h1>

    <form action="{% url 'front:add' %}" method="post">
        {% csrf_token %}
        {{ form }} 
        <input type="submit">
    </form>

    <script src="" async defer></script>
    
{% endblock body %}
    

front/templates/front/base.html
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Taski</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        {% block body %}
        {% endblock %}

    </body>
</html>

front/templates/front/index.html
{% extends 'front/base.html' %}

{% block body %}
    <h2>Welcome, to Taski.</h2>

    
    {% for i in tasks %}
        <li>{{ i }}</li>      
    {% endfor %}
        
    <a href="{% url 'front:login' %}">Go to login page.</a>
    <br>
    <a href="{% url 'front:register' %}">Register New User</a>
    <br>
    <a href="{% url 'front:add' %}">Add a New Task.</a>
    <script src="" async defer></script>
{% endblock %}
    

front/templates/front/login.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Login</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'front/index.css' %}">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <h1>Log In</h1>
        <script src="" async defer></script>
    </body>
</html>

front/templates/front/register.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Register</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'front/index.css' % }">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h2>Register</h2>
        <script src="" async defer></script>
    </body>
</html>